name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '28.0/**'
      - '29.0/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [28.0-nextcloud-bookworm, 28.0-nextcloud-database-bookworm, 29.0-nextcloud-bookworm, 29.0-nextcloud-database-bookworm]
        include:
          - version: 28.0-nextcloud-bookworm
            docker-context: 28.0/debian/nextcloud/default
            docker-tags: |
              nicoherbigde/nextcloud:28.0
              nicoherbigde/nextcloud:28.0-bookworm
              nicoherbigde/nextcloud:28.0.8
              nicoherbigde/nextcloud:28.0.8-bookworm
          - version: 28.0-nextcloud-database-bookworm
            docker-context: 28.0/debian/nextcloud-database/default
            docker-tags: |
              nicoherbigde/nextcloud-database:28.0
              nicoherbigde/nextcloud-database:28.0-bookworm
              nicoherbigde/nextcloud-database:28.0.8
              nicoherbigde/nextcloud-database:28.0.8-bookworm
          - version: 29.0-nextcloud-bookworm
            docker-context: 29.0/debian/nextcloud/default
            docker-tags: |
              nicoherbigde/nextcloud:29.0
              nicoherbigde/nextcloud:29.0-bookworm
              nicoherbigde/nextcloud:29.0.1
              nicoherbigde/nextcloud:29.0.1-bookworm
          - version: 29.0-nextcloud-database-bookworm
            docker-context: 29.0/debian/nextcloud-database/default
            docker-tags: |
              nicoherbigde/nextcloud-database:29.0
              nicoherbigde/nextcloud-database:29.0-bookworm
              nicoherbigde/nextcloud-database:29.0.1
              nicoherbigde/nextcloud-database:29.0.1-bookworm

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
